Operations to get elements or properties of an array

In [32]:
import numpy as np

In [33]:
an_array = np.arange(0, 11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [37]:
first_element = an_array[0]
print(first_element)
last_element = an_array[10]
print(last_element)

0
10


In [38]:
first_five = an_array[0:5]
first_five = an_array[:5]
print(first_five)

[0 1 2 3 4]


In [41]:
last_five = an_array[6:]
print(last_five)

[ 6  7  8  9 10]


In [42]:
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [43]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [44]:
print(an_array.size)

11


In [47]:
print(np.average(an_array))

5.0
